title: coding guru
email: no@gmail.com
description: 1 MILLION learners learning Programming, Cloud and DevOps. Check out our roadmaps!
url: 'https://lordbeerus145.github.io/'
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-analytics

# Products
products:
  - name: Articles
    url: /blog
  - name: Roadmaps
    url: https://lordbeerus145.github.io/roadmaps

# Articles
articles:
  - name: Spring Boot
    url: https://lordbeerus145.github.io/blog
  - name: Cloud
    url: https://lordbeerus145.github.io/blog

collections:
  blog:
    output: true

author:
  name: XYZ NAME
  image: assets/images/about/ranga-karanam-profile-nobg.png
  about: XYZ ABOUT 3
  description: 10X certified on AWS, Azure and Google Cloud.

social:
  twitter: https://twitter.com
  linkedin: http://linkedin.com/in/
  github: http://github.com/
  udemy: http://udemy.com/user/
  facebook: https://www.facebook.com/
  youtube: https://www.youtube.com/user/

# google_analytics: UA-32942307-5

# jekyll_analytics:
#   GoogleAnalytics:
#     id: UA-32942307-5

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
